sonar.projectKey=cqrs-lab
sonar.projectName=cqrs lab
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/bin/**,**/obj/**

sonar.sourceEncoding=UTF-8
sonar.cs.vscoveragexml.reportsPaths=coverage.xml
